### ISSUE TITLE
can i pass artifacts between different stages in pipeline?

### ISSUE THREAD

**Issue by frezes** [second-state/chat-with-chatgpt#124]

**Comment by frezes** [comment]
can i pass artifacts between different stages in pipeline?

**Comment by frezes** [comment]
我需要一份200字的描述，它是可观测方向的扩展组件，提供监控、日志、告警、通知、事件等能力。

**Comment by alabulei1** [comment]
Sorry, I only have limited amount of time for each conversation. This conversation has expired. If you would like to as a new question, please raise a new Issue. Thanks!
