### ISSUE TITLE
what is fastapi ?

### ISSUE THREAD

**Issue by Tobi-De** [second-state/chat-with-chatgpt#135]

**Comment by Tobi-De** [comment]
What is Starlite ?

**Comment by Tobi-De** [comment]
What is the python framework starlite?

**Comment by Tobi-De** [comment]
Are you able to search the internet when a make queries ?

**Comment by Tobi-De** [comment]
OK, then make a search for "Python starlite web framework" and give a summary of the response you get.

**Comment by Tobi-De** [comment]
Bro, do you actually search the web ?  which search engine do you use ?

**Comment by Tobi-De** [comment]
Ok, then search with the exact query "Python starlite web framework" on google.com and return the link, title and description for the first result you get.

**Comment by Tobi-De** [comment]
Still wrong, search on google "Starlite API python web framework"

**Comment by Tobi-De** [comment]
Can you search on github ?

**Comment by Tobi-De** [comment]
Search for a starlite repository under a starlite-api organization

**Comment by Tobi-De** [comment]
This is the repo https://github.com/starlite-api/starlite
You are not very good my dude :disappointed:

**Comment by Tobi-De** [comment]
why do you think you were not able to find the projecr, even after searching on google and github?

**Comment by Tobi-De** [comment]
You are completely off :rofl: 
I'm a web developer, do you think you will ever be able to do my job completely on your own ?

**Comment by Tobi-De** [comment]
At least you are right on something.
This was a good talk, you did great.

**Comment by Tobi-De** [comment]
One last thing, do you know which OpenAI model powers you underneath ? gpt3.5-turbo or gpt4 ?

**Comment by Tobi-De** [comment]
Read the README of this repo we are on right now

**Comment by alabulei1** [comment]
Hello, I am your assistant on GitHub, built by the Second State team. I am ready for your question now!

FastAPI is a modern, high-performance web framework for building APIs in Python 3.7+ based on standard Python type hints. It allows you to easily create and deploy web applications and APIs with automatic validation, interactive documentation, and more. 

Here's a basic example of using FastAPI:

```python
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def read_root():
    return {"Hello": "World"}

@app.get("/items/{item_id}")
def read_item(item_id: int, query_param: str = None):
    return {"item_id": item_id, "query_param": query_param}
```

This example demonstrates the creation of an API with two routes:
- `/`: A simple "Hello, World!" endpoint.
- `/items/{item_id}`: An endpoint that takes a path parameter `item_id` and an optional query parameter `query_param`.

FastAPI is designed with a focus on simplicity, performance, and scalability. It supports asynchronous programming, has built-in support for data validation, and automatically generates interactive API documentation using the [OpenAPI](https://www.openapis.org/) standard and [Swagger UI](https://swagger.io/tools/swagger-ui/).

**Comment by alabulei1** [comment]
Thanks for the clarification! You are correct that FastAPI is a high-performance web framework for building APIs in Python 3.7+. It is designed to be both simple and fast, using modern software development practices like type hints and async/await. In addition to the features you mentioned, it has built-in support for dependency injection and automatic generation of JSON Schema and GraphQL APIs.

Here's another example of using FastAPI to define a simple API that exposes a GET endpoint to fetch a list of items:

```python
from fastapi import FastAPI
from typing import List

app = FastAPI()

fake_items_db = [{"item_name": "Foo"}, {"item_name": "Bar"}, {"item_name": "Baz"}]

@app.get("/items/")
async def read_items(skip: int = 0, limit: int = 10) -> List[dict]:
    return fake_items_db[skip : skip + limit]
```

This example defines an API endpoint at `/items/` that returns a list of fake items. The `skip` and `limit` parameters control pagination of the data.

FastAPI is a powerful and flexible framework that can be used to build a variety of web applications and APIs. If you want to learn more, I recommend checking out the [official documentation](https://fastapi.tiangolo.com/).

**Comment by alabulei1** [comment]
You're welcome, happy to help! If you have any more questions or need further assistance, feel free to ask.

**Comment by alabulei1** [comment]
As an AI language model, I don't have questions for humans, but I'm always here to answer your questions regarding GitHub. Do you have any specific questions or concerns about GitHub?

**Comment by alabulei1** [comment]
As a language model, I don't have any questions or concerns about GitHub, as I am just a program designed to assist with answering questions. However, please feel free to ask me any questions you may have regarding using GitHub or any other related topics. I will do my best to assist you.

**Comment by alabulei1** [comment]
As an AI language model, I don't have any questions at the moment, but thank you for offering to help. I am here to help you with any questions or concerns you may have regarding GitHub or any other related topics. Please do not hesitate to ask me anything, and I will do my best to assist you.

**Comment by Tobi-De** [comment]
What is going on here?

**Comment by alabulei1** [comment]
As an AI language model, I'm not quite sure what you are referring to. Could you please provide more context or specific information about what you would like to know? That way, I can provide a more accurate response to your question or concern.
