### ISSUE TITLE
what are you?

### ISSUE THREAD

**Issue by blazeqin** [second-state/chat-with-chatgpt#164]

**Comment by alabulei1** [comment]
Hello, I am your assistant on GitHub, built by the Second State team. I am ready for your question now!
```

**Comment by juntao** [comment]
Hello

**Comment by alabulei1** [comment]
Sorry, I only have limited amount of time for each conversation. This conversation has expired. If you would like to as a new question, please raise a new Issue. Thanks!

**Comment by alabulei1** [comment]
Not a problem! Feel free to come back whenever you need assistance. Have a good day!
