### ISSUE TITLE
April fools

### ISSUE THREAD

**Issue by juntao** [second-state/chat-with-chatgpt#219]
What is the origin of April fool's day?

**Comment by alabulei1** [comment]
April Fool's Day, also known as All Fools' Day, is celebrated on April 1st each year. The exact origin of this tradition is not entirely clear, but there are a few theories. 

One theory suggests that it dates back to when the Gregorian calendar was introduced in France in the 16th century. Those who continued to observe the old Julian calendar, which began the new year on April 1st, were mocked and made fun of by those who had adopted the new calendar, with pranks and fake invitations to non-existent parties being common.

Another theory suggests that it may be related to ancient spring festivals, such as Hilaria, which were held around the end of March and involved people playing practical jokes on each other. 

Regardless of its origin, April Fool's Day is now celebrated in various parts of the world with pranks, hoaxes, and practical jokes being played on family, friends, and sometimes even coworkers.

**Comment by juntao** [comment]
Does China celebrate April fool's day?

**Comment by alabulei1** [comment]
April Fool's Day is not widely celebrated in China as it is observed mostly in Western cultures. However, in recent years, with the rise of globalization and social media, some people in China have started to celebrate it by playing pranks and making jokes on April 1st. For example, websites and companies in China sometimes create humorous fake news stories, and some individuals may play practical jokes on their friends and family. However, it is not an official holiday or widely celebrated tradition in China.

**Comment by juntao** [comment]
Can you tell me about the famous pranks played on April fool's day in history?

**Comment by alabulei1** [comment]
Sure! There have been many famous pranks played on April Fool's Day throughout history. Here are a few notable ones:

1. The Swiss Spaghetti Harvest: In 1957, the British news show "Panorama" ran a segment about a Swiss town's spaghetti harvest, complete with footage of people harvesting spaghetti strands from trees. The segment was, of course, completely fake, but many viewers believed it and called in to ask how they could grow their own spaghetti trees.

2. The Left-Handed Whopper: In 1998, Burger King ran a full-page ad in USA Today announcing the release of a new burger designed specifically for left-handed people. The ad claimed that all of the condiments in the Left-Handed Whopper would be rotated 180 degrees. The prank was so convincing that many Burger King locations received orders for the "new" burger.

3. Sidd Finch: In 1985, Sports Illustrated ran an article about a new pitcher for the New York Mets named Sidd Finch, who could reportedly throw a fastball at 168 miles per hour. The article was, of course, a complete hoax, but many readers believed it and were amazed by Finch's supposed abilities.

4. The Eruption of Mount Edgecumbe: In 1974, residents of Sitka, Alaska, woke up to find smoke billowing out of the long-dormant volcano Mount Edgecumbe. However, it soon became clear that the smoke was actually coming from 70 old tires and a large pile of wood that had been set on fire inside the volcano's crater as part of an April Fool's Day prank.

These are just a few examples of the many famous April Fool's Day pranks that have been played throughout history!

**Comment by juntao** [comment]
Are there notable pranks after 2000?

**Comment by alabulei1** [comment]
Yes, there have been many notable pranks played on April Fool's Day after 2000. Here are a few examples:

1. Google Maps: In 2018, Google Maps announced that they were adding a new feature called "Where's Waldo?" that allowed users to search for the popular children's book character on their maps. This was a collaboration with the creators of the "Where's Waldo?" books and included a Waldo-themed mini-game.

2. Selfie Shoes: In 2015, Miz Mooz announced a new product called Selfie Shoes, which were high heels with a smartphone dock on the toe, allowing the wearer to take selfies from a new angle. The product was, of course, a complete joke, but the video announcing it went viral and was viewed millions of times.

3. IKEA Dog Highchair: In 2019, IKEA announced a new product called the "Lurvig Dog Highchair," which was a high chair designed specifically for dogs. The prank included an instructional video and even a mock-up of the product on the IKEA website.

4. Netflix Live: In 2017, Netflix released a video announcing a new feature called Netflix Live, which was supposed to be a live-streamed talk show hosted by comedian Will Arnett. The video included fake audience reactions and even teasers for upcoming guests (including 30 different pictures of Adam Sandler). 

These are just a few examples of the many fun and creative April Fool's Day pranks that have been played in recent years!
