### ISSUE TITLE
特朗普为什么被逮捕

### ISSUE THREAD

**Issue by shiqiangguo** [second-state/chat-with-chatgpt#247]

**Comment by alabulei1** [comment]
目前为止，特朗普并没有被逮捕。他曾经被弹劾，但在2020年2月被参议院宣判无罪。您可能听说了特朗普团队中的一些人员或支持者因暴力事件或其他法律问题而被捕，但特朗普本人目前没有被逮捕。

**Comment by shiqiangguo** [comment]
特朗普为什么被叫做川建国

**Comment by alabulei1** [comment]
“川建国”是特朗普在中国网络上的昵称，源自于“让美国再次伟大”(Make America Great Again)的缩写MAGA，而在中文里，该音节读作“川建国”。这一称谓最早由中国网民在社交媒体上使用，但并不是特朗普自己所使用。因为该称呼流行于中国互联网，因此有人会将其用于特朗普的相关报道或评论中。
