### ISSUE TITLE
Please write a python script that can add properties to the image's manifest.json file in by calling Jfrog artifactory API

### ISSUE THREAD

**Issue by hyfj44255** [second-state/chat-with-chatgpt#256]

**Comment by alabulei1** [comment]
Sure, here's a sample Python script that uses the JFrog Artifactory API to add properties to an image's `manifest.json` file:

```python
import requests
import json

# Set the variables for the API request
artifactory_url = "https://my-artifactory.com/api/storage/docker-local/my-image/manifest.json?properties=myprop=newvalue"
api_key = "MY_API_KEY"

# Set the headers for the API request, including the API key
headers = {
  "X-JFrog-Art-Api": api_key,
  "Content-Type": "application/json"
}

# Use the requests library to send the API request
response = requests.put(artifactory_url, headers=headers)

# Check the response status code to make sure the request was successful
if response.status_code == 200:
  print("Properties added successfully.")
else:
  print("Error adding properties. Status code: ", response.status_code)
```

In this script, you'll need to replace `my-artifactory.com`, `MY_API_KEY`, `docker-local`, and `my-image` with your own values specific to your Artifactory instance and image. 

You can modify the `properties` value in the `artifactory_url` variable to add your desired properties to the manifest file. If you want to add multiple properties, separate them with a semicolon, like this: `properties=myprop1=value1;myprop2=value2`. 

I hope this helps! Let me know if you have any questions.
