### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by musabibnusiraj** [second-state/chat-with-chatgpt#286]
Testing the chat gpt with flows

**Comment by alabulei1** [comment]
Hello, I am your assistant on GitHub, built by the Second State team. I am ready for your question now! What can I do for you today?

**Comment by musabibnusiraj** [comment]
i need a simple ghost story

**Comment by alabulei1** [comment]
Sure, here's a short ghost story for you:

There was an old, abandoned house at the end of the street that everyone in the neighborhood avoided. Legend had it that the previous owner of the house had gone insane and killed his family before taking his own life.

One night, a group of teenagers dared each other to go inside the house and explore. As they made their way to the attic, they heard strange noises and felt icy gusts of wind. Suddenly, a figure appeared before them, dressed in old-fashioned clothes and with hollow eyes. It was the ghost of the former owner of the house - still haunting it years after his death.

Terrified, the teenagers ran out of the house and never ventured back there again. But they couldn't shake the feeling that the ghost was still lingering, waiting for its next victim.

**Comment by musabibnusiraj** [comment]
Test

**Comment by alabulei1** [comment]
Hello! How can I assist you today?
