### ISSUE TITLE
Attempt 1 

### ISSUE THREAD

**Issue by Aashmit** [second-state/chat-with-chatgpt#289]
Hi chatgpt

**Comment by alabulei1** [comment]
Hello, I am your assistant on GitHub, built by the Second State team. I am ready for your question now!

**Comment by Aashmit** [comment]
is there any way an issue to be made private on github

**Comment by alabulei1** [comment]
Yes, it is possible to create a private issue on GitHub. Private issues are only visible to people who have been granted access to the repository. To create a private issue, you need to have the necessary permissions to the repository.

Here are the steps to create a private issue:

1. Navigate to the GitHub repository where you want to create a private issue.
2. Click on "Issues" tab and then the "New issue" button.
3. Click the "Set label" dropdown, and select "Private" or create your own label.
4. Then, type your issue description, title and click on the "Submit new issue" button to create the private issue.

Once you create a private issue, only authorized users will be able to access and view it. So, you can discuss sensitive information without the worry of it being publicly visible.

Note that private issues are only available to paid accounts and are not included in the free tier.
